
export default [
    {
        key: '1',
        name: 'ali Brown',
        age: 1,
        address: 'ali house address',
    },
    {
        key: '2',
        name: 'Jim Green',
        age: 2,
        address: 'jim green house address',
    },
    {
        key: '3',
        name: 'Joe Black',
        age: 3,
        address: 'joe black house address',
    },
    {
        key: '4',
        name: 'jhon white',
        age: 4,
        address: 'jhon white house address',
    },
    {
        key: '5',
        name: 'lee Brown',
        age: 5,
        address: 'lee brown house address',
    },
    {
        key: '6',
        name: 'Jim Green',
        age: 6,
        address: 'London No. 1 Lake Park',
    },
    {
        key: '7',
        name: 'Joe Black',
        age: 7,
        address: 'Sidney No. 1 Lake Park',
    },
    {
        key: '8',
        name: 'jhon white',
        age: 8,
        address: 'Sidney No. 1 Lake Park',
    },{
        key: '9',
        name: 'John Brown',
        age: 9,
        address: 'New York No. 1 Lake Park',
    },
    {
        key: '10',
        name: 'Jim Green',
        age: 10,
        address: 'London No. 1 Lake Park',
    },
    {
        key: '11',
        name: 'Joe Black',
        age: 11,
        address: 'Sidney No. 1 Lake Park',
    },
    {
        key: '12',
        name: 'jhon white',
        age: 12,
        address: 'Sidney No. 1 Lake Park',
    },
    {
        key: '13',
        name: 'John Brown',
        age: 13,
        address: 'New York No. 1 Lake Park',
    },
    {
        key: '14',
        name: 'Jim Green',
        age: 14,
        address: 'London No. 1 Lake Park',
    },
    {
        key: '15',
        name: 'kal Black',
        age: 15,
        address: 'Sidney No. 1 Lake Park',
    },
    {
        key: '16',
        name: 'jhon white',
        age: 16,
        address: 'Sidney No. 1 Lake Park',
    },
    {
        key: '17',
        name: 'John Brown',
        age: 17,
        address: 'New York No. 1 Lake Park',
    },
    {
        key: '18',
        name: 'Jim Green',
        age: 18,
        address: 'London No. 1 Lake Park',
    },
    {
        key: '19',
        name: 'Joe Black',
        age: 19,
        address: 'Sidney No. 1 Lake Park',
    },
    {
        key: '20',
        name: 'jhon white',
        age: 20,
        address: 'Sidney No. 1 Lake Park',
    },{
        key: '21',
        name: 'John Brown',
        age: 21,
        address: 'New York No. 1 Lake Park',
    },
    {
        key: '22',
        name: 'Jim Green',
        age: 22,
        address: 'London No. 1 Lake Park',
    },
    {
        key: '23',
        name: 'Joe Black',
        age: 23,
        address: 'Sidney No. 1 Lake Park',
    },
    {
        key: '24',
        name: 'jhon white',
        age: 24,
        address: 'Sidney No. 1 Lake Park',
    },
]; 